Warning modal
yalla-coop/curenetics pull request #158
Opened 2019-11-14 23:19 UTC by wright1

This branch relates to issue #137 . Warning modal pops-up when you want to leave editPatient page.

2019-11-15 10:34 UTC, thejoefriel requested changes
- The modal is fixed to the top and instead needs to be in the middle. If this is getting fixed tough in #159 then just let me know and it can be ignored on this PR
- The warning also just needs to be added to the following pages:
    - [x] /patient-list
    - [x] /trial-list
    - [x] /match-trial

Other than that it looks good :)

2019-11-20 09:44 UTC, MohammedYehia commented
This seems good to me but is the responsiveness fixed for this modal also?
if so then it's fine for me to merge after fixing the conflict

2019-11-28 13:15 UTC, MohammedYehia approved these changes

2019-11-29 15:41 UTC, MohammedYehia approved these changes

2019-11-29 15:50 UTC, merged