initial ui setup
yalla-coop/curenetics pull request #55
Opened 2019-09-29 16:26 UTC by mr-bagglesworth

- Includes setup for home, about, 404, upload details, and enter details manually
- Covers main ui building blocks separated into Layout, Typography, Buttons, and Forms
- Omitted results and edit patient data as these are more dynamic routes that rely upon API interaction.

**To discuss:**
- design inconsistencies and ambiguities in [figma mockup](https://www.figma.com/file/BaIHfKxJN8zhXlVoTxlTJu7B/CURENETICS2?node-id=47%3A1181)
- would strongly suggest using material ui select for dropdowns

2019-09-29 21:12 UTC, mr-bagglesworth commented
Will not push any more commits to this branch now, please feel free to merge, or amend and merge.

2019-09-30 07:51 UTC, othman-shamla requested changes

2019-09-30 07:51 UTC, othman-shamla commented on src/components/App.js
> +    <Fragment>
you can just put replace <Fragment> </Fragment> with <> </> 
its more cleaner i think

2019-09-30 07:51 UTC, othman-shamla commented on src/components/common/Buttons.js
> +const buttonReset = css`
here you can export the variable in the same line by putting  export before const
```
export const buttonReset = css`
```
there is no need to write the variable twice to exported

2019-09-30 21:59 UTC, mr-bagglesworth commented
@othman-shamla requested amends completed. Also:
- amended breadcrumb / back button
- added remaining icons + visually tested in `ResultDetails.js`

2019-10-01 04:30 UTC, othman-shamla commented
thanks @mr-bagglesworth i will merge the PR

2019-10-01 04:31 UTC, othman-shamla approved these changes

2019-10-01 04:31 UTC, merged