Feature/view match trials
yalla-coop/curenetics pull request #79
Opened 2019-10-09 07:26 UTC by othman-shamla

### NOTES
* page need refactor to match other pages structure

2019-10-10 09:48 UTC, wright1 reviewed
@othman-shamla  Is there a reason why data isn't entered as props?
You did a great job with layout and styling what I would say is that it looks a bit squashed on the page. It would be a bit easier on the eye if there was more space around the text.

2019-10-10 10:16 UTC, othman-shamla commented
i just build the layout and the style for the page, didn't continue and was waiting for the filter function to finish

2019-10-10 10:40 UTC, susanX commented
The Desktop layout looks good, do not add more space.
I would like to see it with the real data. How is that going? 
The Mobile layout is working very well. I like the one item a line. Very nice! 
Susan

2019-10-10 11:55 UTC, othman-shamla commented
this is will be in separate PR 
@susanX

2019-10-10 12:07 UTC, MohammedYehia requested changes
@othman-shamla 
You should not use the Grid system as this is not supported by Internet Explorer
refer to issue #32 
@thejoefriel What do you think?
use flexbox or maybe you can use Row and Col from antd
also, take another look to the Figma design and to the margins, the font size, and weight 
I pushed PR for a polyfill for React and antd to work on IE

2019-10-10 12:36 UTC, othman-shamla commented
@MohammedYehia  what about flex-box? does it work?

2019-10-10 12:41 UTC, othman-shamla commented
if that so we need to change the style for patient-list also

2019-10-10 12:44 UTC, MohammedYehia commented
Yes flexbox is supported and ant design also work with Internet Explorer

2019-10-11 07:56 UTC, wright1 commented
@othman-shamla 
Small point -> the color of the "TableHeadColor" will need to be conditionally rendered.

2019-10-13 11:26 UTC, martinbagshaw requested changes
Hi Othman,

There are a few points in my review that need addressing, a couple of which require a further discussion and agreements with the team. A couple of other points that I haven't mentioned below:

- Please add a bit more spacing, and refer back to the [design](https://www.figma.com/file/BaIHfKxJN8zhXlVoTxlTJu7B/CURENETICS2?node-id=47%3A1181). Not far off though, good effort.
- Would probably be more time efficient to re-use components defined in `Layout.js` and `Buttons.js` in particular.

**Table labels for different screen sizes**

I can see you aren't a user of hooks yet, but this little snippet may be a good in-road for you, and avoid having to pass down a single prop through 2 components.

**1. create a file with the following code:**
- This detects screensize, and returns the boolean `true` if the screen size is under 768px (tablet size).
- [useEffect hook](https://reactjs.org/docs/hooks-effect.html) lets you perform the side-effect of accessing the window

```javascript
import { useEffect, useState } from 'react';

export const useIsTablet = (width = '768px') => {
  const check = window.matchMedia(`(max-width: ${width})`);
  const [state, setState] = useState(check);

  const checkIsTablet = () => {
    if (state !== check.matches) {
      setState(check.matches);
    }
  };

  useEffect(() => {
    check.addListener(checkIsTablet);
    return () => {
      check.removeListener(checkIsTablet);
    };
  });

  checkIsTablet();
  return { IsTablet: check.matches };
};
```

**2. Set up the `<Table />` component something like this:**

```javascript
import React from 'react';
import { useIsTablet } from './your-file-above';

const Table = {
// if isTablet = true, the screen width is 768px or under
// therefore !isTablet will return true for screens that are > 768px wide
const { IsTablet } = useIsTablet();
  return (
    <Table>
      <TableHeader>
        <span>Trial {!IsTablet && 'criteria'}</span>
        <span>Patient {!IsTablet && 'details'}</span>
      </TableHeader>
      <TableBody>
        <span>Some content for **all** screen sizes</span>
        {!IsTablet &&
         <span>Some content for screen sizes **over 768px**</span>
        }
      </TableBody>
    </Table>
  );
};
```

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/common/icons/ExportLink.jsx
> +const ExportLink = ({ titleTag = 'External Link', width = 24, fill = '#ffffff', margin = "initial" }) => (
This may have knock on effects for other instances of `ExportLink`

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/cardMatch.js
> +import * as S from './style';
Doesn't follow coding style used most other places in the app. Ultimately this is a team decision, and something we should all discuss. May make it harder for others to pick up your code.

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/cardMatch.js
> +const matchCard = ({ windowWidth }) => {
I see you are passing this down from `index.js` through `cardmatch` / `matchCard` to simply render different text within the `<Table />` component, but also duplicating code for the table in the process. This can be done in a much simpler way using a hook required by `<Table />`, and an object containing text for each field for small screen sizes and large screen sizes. I will add some code to demo in my final review comment.

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/cardMatch.js
> +              <Avatar></Avatar>
This and with other icons are **self closing elements**. They have no content in between their opening and closing tags, and so can be written like `<Avatar />`. You can also provide a custom title tag by doing:
```javascript
<Avatar titletag='Phase of the Trial' />
```

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/cardMatch.js
> +          <S.PrimarySpam>NCT Number: </S.PrimarySpam>
Make a dummy data object with a data structure similar to a **trial result** in the trials API. Feed this into this component to **dynamically** display the data. Other examples are in the app at the moment. See #96

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/cardMatch.js
> +        <S.FieldWrapper style={{ gridColumn: '2/4' }}>
As per Mohammed's comment regarding IE11, if we aren't using grid, change to flexbox. [This](https://developer.mozilla.org/en-US/docs/Web/CSS/flex) may help when defining a child flex element's width and position in the flex container.

Also, remove inline styles.

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/cardMatch.js
> +      <Table windowWidth={windowWidth} />
See above comment regarding windowWidth and table content / labels

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/cardMatch.js
> +            <ExportLink margin="0px 0px 0px 10px"></ExportLink>
Self closing element, as per comment above. This would be:

```javascript
<ExportLink margin="0px 0px 0px 10px" />
```

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/headerMatch.js
> +import 'antd/dist/antd.css';
Why is this here? We don't seem to be using the dropdown here? Please let me know if there is something here I have missed.

In any case, it would be less confusing to add styles that cover multiple components in a central location, rather than porting them over from one component to another.

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/index.js
> +    const { windowWidth } = this.state;
See window width / table label content comment above ^

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/table.js
> +  if (windowWidth < +breakpoint.tablet.split('px')[0]) {
Last comment, above

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/table.js
> +        <div style={{ padding: '0rem 0rem 1rem 0rem' }}>
Avoid inline styles.

2019-10-13 11:26 UTC, martinbagshaw commented on src/components/pages/matchTrial/table.js
> +        <S.TableHeadColor></S.TableHeadColor>
Is this doing anything at all? You have opened and closed an element. Unless this is an `<svg>` or `<img>`, its styling can _probably_ be applied to the parent or the child element.

2019-10-13 11:26 UTC, mr-bagglesworth commented on src/components/pages/matchTrial/style.js
> +  font-weight: 900;
I realise there is no variable defined for this in `globalStyles.js`, which we may want, just to make things clear.
In `Typography.js`, we don't import a font with weight of 900. Use **700** instead:

<img width="704" alt="Screenshot 2019-10-13 at 12 01 18" src="https://user-images.githubusercontent.com/28146666/66714674-7b970580-edb1-11e9-9c22-c80851b1da27.png">

2019-10-13 11:26 UTC, mr-bagglesworth commented on src/components/pages/matchTrial/cardMatch.js
> +          <span style={{ gridColumn: '1 / 3' }}>
This looks like a clickable link, and therefore should be an anchor link. I believe there is a pre-made anchor link defined in `Buttons.js` for this.

<img width="307" alt="Screenshot 2019-10-13 at 11 21 46" src="https://user-images.githubusercontent.com/28146666/66714688-af722b00-edb1-11e9-912f-9a735dbec610.png">

2019-10-16 11:49 UTC, wright1 approved these changes

2019-10-16 14:30 UTC, merged