add the support for IE 11 #94
yalla-coop/curenetics pull request #95
Opened 2019-10-10 12:10 UTC by MohammedYehia

closes #94 
add the support for IE 11 as currently, the app is not working on IE 11

2019-10-11 00:15 UTC, martinbagshaw requested changes
Not necessarily requesting changes here, but are you sure that this will cover everything we need to make the app work on IE11? Should we try to roll all IE support related changes into one PR?

I ask because, at a glance, the [npm page](https://www.npmjs.com/package/react-app-polyfill) mentions the es6 features that this would provide polyfills for. So theoretically, this would be javascript covered.

Regarding your earlier mention of css grid on slack, I think we can probably find a workaround in the case that the above just covers javascript. Perhaps some avenues to explore:
- use the `-ms` prefix to style grid containers from their parent. I think an example of this sort of thing would be in some of the styling I did for `antd` - as I did not have direct access to html within the dropdown. This approach will give us duplicate styles to maintain (for IE) though.
- [medium article which gave me hope earlier](https://medium.com/@elad/supporting-css-grid-in-internet-explorer-b38669e75d66) - just said grid gap isn't supported, in which case we can use a margin instead.
- [this article sounds pretty good](https://www.webstoemp.com/blog/notes-on-using-css-grid-in-production/)
- If all else fails, use flexbox. Not as precise as grid can be, but still we can work something out.

2019-10-13 12:37 UTC, MohammedYehia commented
@mr-bagglesworth  this to add Javascript compatibility to IE browser nothing has to do with grid system (this is just to make a react app run on IE browser)
 
and for the grid system, I don't see any point of going throw all this pain of reading articles and thinking twice before applying any CSS property why not using something that we are 100% sure it will work? everything can be done with **flex-box** and antd

2019-10-16 08:30 UTC, wright1 approved these changes

2019-10-16 09:25 UTC, othman-shamla approved these changes

2019-10-16 10:25 UTC, merged